#
# mm: the PHP media library
#
# Copyright (c) 2007-2013 David Persson
#
# Distributed under the terms of the MIT License.
# Redistributions of files must retain the above copyright notice.
#
# @copyright  2007-2013 David Persson <nperson@gmx.de>
# @license    http://www.opensource.org/licenses/mit-license.php The MIT License
# @link       http://github.com/davidpersson/mm
#
language: php

php:
  - 5.3
  - 5.4

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install ghostscript
  - sudo apt-get -qq install imagemagick
  - sudo apt-get -qq install ffmpeg
  - sudo apt-get -qq install sox
  - printf "\n" | pecl install imagick

before_script:
  - uname -a
  - convert --version
  - gs --version
  - ffmpeg -version
  - sox --version
  - php -m